import { createHash } from "crypto";
import { spotifyConfig } from "@/lib/config";
import type { SpotifySession } from "@/lib/session";
export type Profile = { display_name: string | null; id: string };
export type Playback = { is_playing: boolean; item: { name: string; artists: { name: string }[] } | null };
export type Device = { name: string; type: string; is_active: boolean };
export const challengeFor = (verifier: string) => createHash("sha256").update(verifier).digest("base64url");
export async function exchangeCode(code: string, verifier: string): Promise<SpotifySession> { const { clientId, redirectUri } = spotifyConfig(); const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: clientId, grant_type: "authorization_code", code, redirect_uri: redirectUri, code_verifier: verifier }), cache: "no-store" }); const data = await response.json(); if (!response.ok || !data.access_token || !data.refresh_token) throw new Error("Spotify token exchange failed"); return { accessToken: data.access_token, refreshToken: data.refresh_token, expiresAt: Date.now() + data.expires_in * 1000, scope: data.scope ?? "" }; }
export async function validSession(s: SpotifySession) { if (s.expiresAt > Date.now() + 60000) return s; const { clientId } = spotifyConfig(); const r = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: clientId, grant_type: "refresh_token", refresh_token: s.refreshToken }), cache: "no-store" }); const d = await r.json(); if (!r.ok || !d.access_token) throw new Error("Spotify token refresh failed"); return { accessToken: d.access_token, refreshToken: d.refresh_token ?? s.refreshToken, expiresAt: Date.now() + d.expires_in * 1000, scope: d.scope ?? s.scope }; }
export async function spotifyGet<T>(path: string, token: string): Promise<T | null> { const r = await fetch(`https://api.spotify.com/v1${path}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); if (r.status === 204) return null; if (!r.ok) throw new Error("Spotify data unavailable"); return r.json() as Promise<T>; }
